RR.Admin/Controllers/UserManagementController.cs
using ExcelDataReader;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using RR.Admin.Models;
using RR.AdminService;
using RR.Core;
using RR.Data;
using RR.Dto;
using RR.Dto.Player;
using RR.Repo;
using RR.Service.Email;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RR.Admin.Controllers
{

    [Authorize(Roles = "Admin,Subadmin")]
    public class UserManagementController : Controller
    {
        #region Constructor
        private readonly IUserService _userservice;
        private readonly ICommonService _commonService;
        private readonly IRepository<AspNetRoles, RankRideContext> _repoRoles;
        private readonly IEmailSender _emailSender;

        public UserManagementController(IUserService userService, ICommonService commonService,
            IRepository<AspNetRoles, RankRideContext> repoRoles, IEmailSender emailSender)
        {
            _userservice = userService;
            _commonService = commonService;
            _repoRoles = repoRoles;
            _emailSender = emailSender;
        }

        #endregion

        /// <summary>
        /// User management List View
        /// </summary>
        /// <returns>User Management View</returns>
        [Route("players")]
        [Authorize(Policy = "PagePermission")]
        public IActionResult Index()
        {
            if (TempData["IsSuccess"] != null)
            {
                ViewBag.IsSuccess = "true";
            }
            return View();
        }

        /// <summary>
        /// Update Status
        /// </summary>
        /// <param name="id">A User Id</param>
        /// <returns>user status detail</returns>
        [HttpPost]
        [Route("upadatestatus")]
        public async Task<JsonResult> UpdateStatus(int id)
        {
            try
            {
                await _userservice.UpdateStatus(id);
                var userDetail = await _userservice.GetUserDetail(id);
                return Json(userDetail);
            }
            catch (System.Exception ex)
            {
                return Json(ex.Message);
            }
        }

        /// <summary>
        /// Get User Detail
        /// </summary>
        /// <param name="id">User Id</param>
        /// <returns>User Detail</returns>
        [HttpPost]
        [Authorize(Policy = "PagePermission")]
        public async Task<JsonResult> GetUserDetail(int id)
        {
            try
            {
                var userDetail = await _userservice.GetUserDetail(id);
                userDetail.CountryName = await _commonService.GetCountryById(userDetail.Country);
                userDetail.StateName = await _commonService.GetStateById(userDetail.State);
                userDetail.CityName = userDetail.City;

                return Json(userDetail);
            }
            catch (System.Exception ex)
            {
                return Json(ex.Message);
            }
        }

        /// <summary>
        /// Update User Detail
        /// </summary>
        /// <param name="id">User Id</param>
        /// <returns>User Detail</returns>
        [Route("player/detail/{id}")]
        [Authorize(Policy = "PagePermission")]
        public async Task<IActionResult> EditUserDetail(int id)
        {
            try
            {
                var userDetail = await _userservice.GetUserDetail(Convert.ToInt32(id));

                var countryList = await _commonService.GetCountries();
                var cityList = await _commonService.GetCitiesByCountryId(Convert.ToInt32(userDetail.Country));
                var stateList = await _commonService.GetStates(Convert.ToInt32(userDetail.Country));

                userDetail.CountryList = countryList;
                userDetail.CityList = cityList;
                userDetail.StateList = stateList;
                userDetail.UserRoleList = GetUserRoleList();
                return View(userDetail);
            }
            catch (System.Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUserDetail(UserDetailDto userDto)
        {
            try
            {
                await _userservice.AddEditUserDetail(userDto);
                await _userservice.UpdateUserRole(userDto.UserId, userDto.PlayerType);
                TempData["IsSuccess"] = "true";
                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Get States
        /// </summary>
        /// <param name="countryId">Country Id</param>
        /// <returns>List Of States Of Given Country Id</returns>

        [Route("states")]
        public async Task<JsonResult> GetStates(int countryId)
        {
            try
            {
                return Json(await _commonService.GetStates(countryId));
            }
            catch (System.Exception ex)
            {
                return Json(ex.Message);
            }

        }

        /// <summary>
        /// Get Cities
        /// </summary>
        /// <param name="stateId">The StateId</param>
        /// <param name="countryId">The CountryId</param>
        /// <returns>List Of All Cities Of Given StateId or CountryId</returns>

        [Route("cities")]
        public async Task<JsonResult> GetCities(int stateId, int countryId)
        {
            try
            {
                var cities = await _commonService.GetCitiesByStateId(stateId);
                if (stateId == 0)
                {
                    cities = await _commonService.GetCitiesByCountryId(countryId);
                }
                return Json(cities);
            }
            catch (System.Exception ex)
            {
                return Json(ex.Message);
            }

        }

        /// <summary>
        /// Unlock User
        /// </summary>
        /// <param name="userName"></param>
        /// <returns></returns>

        [HttpPost]
        [Route("updateuserlockstatus/")]
        [Authorize(Policy = "PagePermission")]
        public async Task<JsonResult> Updateuserlockstatus(string userName)
        {

            var data = await _userservice.Updateuserlockstatus(userName);

            return Json(new
            {
                status = data
            });
        }


        [HttpPost]
        public async Task<JsonResult> GetCurrentPageUsers()
        {
            var draw = Request.Form["draw"];
            var start = Request.Form["start"];
            var length = Request.Form["length"];


            //Global search field
            var search = Request.Form["search[value]"].FirstOrDefault();

            int pageSize = !(string.IsNullOrEmpty(length)) ? Convert.ToInt32(length) : 0;
            int skip = !(string.IsNullOrEmpty(start)) ? Convert.ToInt32(start) : 0;
            var sort = Request.Form["order[0][dir]"];
            var column = Convert.ToInt32(Request.Form["order[0][column]"]);

            var users = await _userservice.GetAllExistUsers(skip / pageSize, pageSize, column, search, sort);

            var data = users.Item1;
            int recordsTotal = users.Item2;

            return Json(new
            {
                draw,
                recordsFiltered = recordsTotal,
                recordsTotal,
                data
            });
        }
        /// <summary>
        /// Delete Cms
        /// </summary>
        /// <param name="id">user Id</param>
        /// <returns></returns>
        [Authorize(Policy = "PagePermission")]
        [Route("deluser/{id}")]
        public async Task<string> DeleteUser(long id)
        {

            bool deleted = await _userservice.DeleteUserByID(id);

            if (deleted)
            {
                return "success";
            }
            else
            {
                return "failed";
            }



        }

        public List<SelectListItem> GetUserRoleList()
        {
            List<SelectListItem> list = new List<SelectListItem>();

            list.Insert(0, new SelectListItem() { Text = "Play For FREE", Value = "NOVICE PLAYER" });
            list.Insert(1, new SelectListItem() { Text = "Top Gun Tour", Value = "INTERMEDIATE PLAYER" });
            list.Insert(2, new SelectListItem() { Text = "Mega Buck Thunder", Value = "PRO PLAYER" });

            return list; /*_repoRoles.Query().Get().ToList().Select(x=>new SelectListItem() { Value=x.NormalizedName, Text= })*/
        }

        [Route("BulkNotifications")]
        public async Task<IActionResult> Notifications()
        {
            return View();
        }

        [HttpPost]
        [Route("BulkNotifications")]
        public async Task<JsonResult> Notifications(IFormFile Excel, string Notify)
        {
            if (Excel.Length > 0 && !string.IsNullOrEmpty(Notify))
            {
                try
                {
                    using (var stream = Excel.OpenReadStream())
                    {
                        // Auto-detect format, supports:
                        //  - Binary Excel files (2.0-2003 format; *.xls)
                        //  - OpenXml Excel files (2007 format; *.xlsx, *.xlsb)
                        using (var reader = ExcelDataReader.ExcelReaderFactory.CreateReader(stream))
                        {

                            //// 1. Use the reader methods
                            //do
                            //{
                            //    while (reader.Read())
                            //    {
                            //        //We don't need an empty object
                            //        //var firstName = reader.GetString(0);

RR.Admin/Views/UserManagement/EditUserDetail.cshtml
@model RR.Dto.UserDetailDto
@{
    ViewData["Title"] = "UpdatePlayerDetail";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Player Detail</h4>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("UpdateUserDetail", "UserManagement", FormMethod.Post))
                    {
                        @Html.HiddenFor(x => x.Id)
                        @Html.HiddenFor(x => x.IsActive)
                        @Html.HiddenFor(x => x.UserId)
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Player Name</label>
                                    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.UserName)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">First name</label>
                                    @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.FirstName)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Last name</label>
                                    @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.LastName)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Email Address</label>
                                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @readonly = "readonly" })
                                    @Html.ValidationMessageFor(x => x.Email)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Phone Number</label>
                                    @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.PhoneNumber)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Country</label>
                                    @Html.DropDownListFor(model => model.PlayerType, Model.UserRoleList, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Country)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Address1</label>
                                    @Html.TextBoxFor(x => x.Address1, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Address1)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Address2</label>
                                    @Html.TextBoxFor(x => x.Address2, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Address2)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Address3</label>
                                    @Html.TextBoxFor(x => x.Address3, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Address3)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Country</label>
                                    @Html.DropDownListFor(model => model.Country, Model.CountryList, "Select Country", new { @onchange = "getstates(this)", @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Country)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">State</label>
                                    @Html.DropDownListFor(model => model.State, Model.StateList, "Select State", new { @onchange = "getcities(this)", @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.State)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">City</label>
                                    @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.City)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Wallet Token</label>
                                    @Html.TextBoxFor(model => model.WalletToken, new { @class = "form-control" })

                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group bmd-form-group is-focused">
                                    <label class="bmd-label-floating">Zip Code</label>
                                    @Html.TextBoxFor(model => model.ZipCode, new { @class = "form-control" })

                                </div>
                            </div>
                        </div>
                        <a href="/players" class="btn btn-primary pull-right">Back To Players</a>
                        <button type="submit" class="btn btn-primary pull-right">Update</button>
                        <div class="clearfix"></div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        function getstates(th) {

            var x = $(th).children("option:selected").val();

            $.ajax({
                type: "Get",
                url: "/states",
                data: { countryId: x },
                success: function (result) {


                    $("#State").empty().append("<option class='state'>Select State</option>");
                    if (result != null && result.length > 0) {
                        $.each(result, function (data, value) {
                            $("#State").append($("<option class='state'></option>").val(value.value).html(value.text));
                        })
                    }
                },
                error: function () {

                }
            });
        }

        function getcities(th) {

            var urs = "/cities"
            var x = $(th).children("option:selected").val();

            $.ajax({
                type: "Post",
                url: urs,
                data: { countryId: $("#Country").children("option:selected").val(), stateId: x },
                success: function (result) {


                    $("#City").empty().append("<option class='city'>Select City</option>");
                    if (result != null && result.length > 0) {
                        $.each(result, function (data, value) {
                            $("#City").append($("<option class='city'></option>").val(value.value).html(value.text));
                        })
                    }
                },
                error: function () {
                    alert("error");
                }
            });
        }
    </script>
}

RR.Admin/Views/UserManagement/Notifications.cshtml
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">Notification Management </h4>
                </div>
                <div class="card-body">
                    <form id="NotifiForm" asp-action="Notifications" data-ajax-begin="onBegin" asp-controller="UserManagement" method="POST"
                          data-ajax="true" data-ajax-success="onNotifySuccess"
                          data-ajax-update="response" enctype="multipart/form-data">

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-wrap is-focused">
                                    <label for="Excel" class="bmd-label-floating">Select Players Excel Data <b>*</b></label>
                                    <input required type="file" name="Excel" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel,text/comma-separated-values, text/csv, application/csv" class="form-control" />
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-wrap is-focused">
                                    <label for="Notify" class="bmd-label-floating">Enter Notification Message <b>*</b></label>
                                    <textarea required name="Notify" class="form-control" rows="5" cols="5"></textarea>
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary btnSubmit" type="submit">Sent Notification</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

                    @section scripts {
                        <script>
                            function onNotifySuccess(response) {
                                debugger;
                                if (!response.status) {
                                    alert(response.message);
                                    console.log(response.message);
                                }
                                else {
                                    swal("Notifications successfully sent!", {
                                        icon: "success",
                                    });
                                }
                                $('#NotifiForm .btnSubmit').prop('disabled', false);
                                $('#NotifiForm')[0].reset();
                            }

                            function onBegin() {
                                if (confirm('Are you sure? you want to sent notifications!')) {
                                    $('#NotifiForm .btnSubmit').prop('disabled', true);
                                    return true;
                                }
                                else {
                                    return false;
                                }
                            }
                        </script>
                    }