RR.Web/Controllers/TeamController.cs
using AppWeb.SignalRHubs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using RR.Core;
using RR.Dto;
using RR.Dto.Team;
using RR.Service;
using RR.Service.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace RR.Web.Controllers
{
    [Authorize(Roles = "TM, PTM, FTM, NTM")]
    public class TeamController : Controller
    {
        #region Constructor

        private readonly UserManager<IdentityUser> _userManager;
        private readonly ITeamService _teamService;
        private readonly IContestService _contestService;
        private readonly IUserService _userService;
        private readonly IEventService _eventService;
        private readonly ILongTermTeamService _longTermTeam;
        //private IHubContext<ChatHub> _hubContext;
        private AppSettings _appsetting;

        public TeamController(UserManager<IdentityUser> userManager,
             ITeamService teamService,
             IContestService contestService,
             IUserService userService,
             IEventService eventService,
             ILongTermTeamService longTermTeam,
             //IHubContext<ChatHub> hubContext,
             IOptions<AppSettings> appsetting
             )
        {
            _userManager = userManager;
            _teamService = teamService;
            _contestService = contestService;
            _userService = userService;
            _eventService = eventService;
            _longTermTeam = longTermTeam;
            //_hubContext = hubContext;
            _appsetting = appsetting.Value;
        }

        #endregion

        /// <summary>
        /// Team Formation Index Page
        /// </summary>
        /// <returns></returns>
        [Route("team-formation/{contestId}/{eventId}/{teamId}")]
        public async Task<IActionResult> TeamFormation(int contestId, int eventId = 0, int teamId = 0)
        {
            TeamFormationDto formationDto = new TeamFormationDto();
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var userInfo = await _userService.GetUserDetail(user.Id);
            var contestInfo = await _contestService.GetContestById(contestId);
            var eventInfo = await _eventService.GetEventById(eventId);

            bool CanEditTeam = (DateTime.Now.AddHours(_appsetting.CanUpdateHr) <= eventInfo.PerfTime);
            if (!CanEditTeam)
            {
                ViewBag.TeamUpdateError = "You can update the team up to 10 minutes before the event starts.";
                return View(formationDto);
            }
            if (contestInfo != null)
            {
                var walletInfo = userInfo.WalletToken.HasValue ? userInfo.WalletToken.Value : 0;
                if (contestInfo.EntryFeeType == "Token" && (contestInfo.JoiningFee > walletInfo))
                {
                    TempData["NoEnoughToken"] = "true";
                    string path = "/event/contest/" + eventInfo.Title.Replace(" ", "-").Replace("/", "%2F") + "/" + eventId;
                    return RedirectToAction("GetContestOfEvent", "Contest", new { eventId = eventId });
                }
            }
            ViewBag.userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.teamId = teamId;
            var joinedContest = await _contestService.GetJoinedContestListByEventId(eventId, user != null ? user.Id : "");

            formationDto = await _teamService.EventPlayersById(eventId, contestId, teamId);
            if (teamId == 0)
                formationDto.IsAlreadyJoined = joinedContest.Contains(contestId) ? true : false;

            return View(formationDto);
        }

       
        /// <summary>
        /// Create Team of Player
        /// </summary>
        /// <param name="teamData">The Team data</param>
        /// <param name="eventId">Event Id</param>
        /// <returns></returns>
        public async Task<ActionResult> CreateTeam(string teamData, int eventId)
        {
            try
            {
                var eventInfo = await _eventService.GetEventById(eventId);

                bool CanEditTeam = (DateTime.UtcNow.AddHours(_appsetting.CanUpdateHr) <= eventInfo.PerfTimeUTC);
                if (!CanEditTeam)
                {
                    return Json(new {timeout=true,message= "You can update the team up to 1 hour before the event starts" });
                }

                var user = _userManager.GetUserId(HttpContext.User);
                if (user != null)
                {
                    var team = JsonConvert.DeserializeObject<IEnumerable<TeamDto>>(teamData);

                    var teamObj = team.FirstOrDefault(x => x.TeamId > 0);
                    var TeamID = teamObj != null ? teamObj.TeamId : 0;
                    
                    if (TeamID > 0)
                     await _teamService.DeleteTeam(TeamID);
                     var teamId = await _teamService.CreateTeam(team, eventId, user);



                    return Json(new
                    {
                        eventId,
                        teamId
                    });
                }
                else
                {
                    return Json(null);
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        /// <summary>
        /// Create long term team 
        /// </summary>
        /// <param name="requestDto">CreateLongTermTeamRequestDto</param>
        /// <returns></returns>
        public async Task<ActionResult> CreateLongTermTeam(CreateLongTermTeamRequestDto requestDto )
        {
            try
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                requestDto.UserId = userId;
                if (userId != null)
                {
                    var team = JsonConvert.DeserializeObject<IEnumerable<LongTermTeamDto>>(requestDto.TeamData);

                    var teamObj = team.FirstOrDefault(x => x.TeamId > 0);
                    var TeamID = teamObj != null ? teamObj.TeamId : 0;
                    if (TeamID > 0)
                        await _longTermTeam.DeleteTeam(TeamID);

                    int newteamId = await _longTermTeam.CreateTeam(team, requestDto);
                    
                    return Json(new
                    {
                        requestDto.TeamId,
                        newteamId
                    });
                }
                else
                {
                    return Json(null);
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        /// <summary>
        /// Team List Page
        /// </summary>
        /// <param name="eventId">EventId</param>
        /// <param name="contestId">Contest Id</param>
        /// <returns></returns>
        //[Route("team/{eventId}/{contestId}")]
        //public IActionResult Index(int eventId, int contestId, int result = 0)
        //{
        //     ViewBag.Result = result;
        //     ViewBag.EventId = eventId;
        //     ViewBag.ContestId = contestId;

        //     return View();
        //}

        //public async Task<JsonResult> TeamList(int eventId, int contestId)
        //{
        //     ViewBag.ContestId = contestId;
        //     var draw = Request.Form["draw"];
        //     var start = Request.Form["start"];
        //     var length = Request.Form["length"];
        //     var user = _userManager.GetUserName(HttpContext.User);

        //     //Global search field
        //     var search = Request.Form["search[value]"];

        //     int pageSize = !(string.IsNullOrEmpty(length)) ? Convert.ToInt32(length) : 0;
        //     int skip = !(string.IsNullOrEmpty(start)) ? Convert.ToInt32(start) : 0;
        //     var sort = Request.Form["order[0][dir]"];
        //     var column = Convert.ToInt32(Request.Form["order[0][column]"]);

        //     var teamList = await _teamService.TeamList(eventId, contestId, user, skip / pageSize, pageSize, column, search, sort);

        //     var data = teamList.Item1;
        //     int recordsTotal = teamList.Item2;

        //     return Json(new
        //     {
        //          draw,
        //          recordsFiltered = recordsTotal,
        //          recordsTotal,
        //          data
        //     });
        //}

        ///// <summary>
        ///// Join Team Contest
        ///// </summary>
        ///// <param name="contestId">Contest Id</param>
        ///// <param name="teamId">Team Id</param>
        ///// <param name="eventId">Event Id</param>
        ///// <returns></returns>
        //[Route("team/joincontest/{teamId}/{contestId}/{eventId}")]
        //public async Task<IActionResult> JoinTeamContest(int contestId, int teamId, int eventId, int trasactionId)
        //{
        //     var joinContest = new JoinedContestDto();
        //     joinContest.ContestId = contestId;
        //     joinContest.TeamId = teamId;
        //     joinContest.UserId = _userManager.GetUserId(HttpContext.User);

        //     await _teamService.AddJoinTeamContest(joinContest);
        //     ViewBag.Result = 1;
        //     return RedirectToAction("index", new { eventId, contestId, result = ViewBag.Result });
        //}
    }
}

RR.Web/Views/Team/Index.cshtml
@model IEnumerable<RR.Dto.TeamLiteDto>
@{
    ViewData["Title"] = "Teams Of User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="section parallax-container breadcrumbs-wrap" data-parallax-img="/images/bg-breadcrumbs-1-1920x726.jpg">
    <div class="parallax-content breadcrumbs-custom context-dark">
        <div class="container">
            <h3 class="breadcrumbs-custom-title">Teams List</h3>
        </div>
    </div>
</section>

<section class="section section-variant-1 bg-gray-100 custom-float-width">
    <div class="container">
        <div class="col-lg-12 custom-bg-gray-100 custom-float-width pad30">
            <div class="table-custom-responsive">
                <a href="@Url.Action("TeamFormation","Team",new { eventId=@ViewBag.EventId})" style=" padding: 10px 20px;background-color: #575a5f;border: none;
                margin: 0;border-radius: 5px;color: #fff;font-size: 14px;float: right;">Create Team</a>
                <table class="table-custom table-standings table-classic table-dark" id="userDataTable">
                    <thead class="card-standing-caption">
                        <tr>
                            <th>TeamId <i class="fa fa-sort"></i></th>
                            <th>Event Name <i class="fa fa-sort"></i></th>
                            <th>User Email <i class="fa fa-sort"></i></th>
                            <th>ContestType <i class="fa fa-sort"></i></th>
                            <th>Join</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</section>

@section Scripts{
    <script src="~/js/bootbox.min.js"></script>
    <script>
        $(function () {
            if (@ViewBag.Result) {
                bootbox.alert("This Team is successfully joined with this contest!!");
            }
            $('.dataTables_filter input').attr('placeholder', 'Search...').hide();
            var table = $("#userDataTable").DataTable({
                "paging": true,
                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once

                //"dom": '<"top"i>rt<"bottom"lp><"clear">',
                "ajax": {
                    "url": '/Team/TeamList',
                    "data": { eventId: @ViewBag.EventId, contestId: @ViewBag.ContestId },
                    "type": "POST",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "id", "name": "id", "autoWidth": false },
                    { "data": "eventName", "name": "eventName", "autoWidth": false },
                    { "data": "userEmail", "name": "userEmail", "autoWidth": false },

                    { "data": "contestType", "name": "contestType", "autoWidth": false },
                    {
                        "data": "teamId", "name": "teamId", "render": function (value) {
                            if (value) {
                                return '<a href="/team/joincontest/' + value + '/' + @ViewBag.ContestId + '/' +@ViewBag.EventId+'" data-token=' + value + ' rel="tooltip" title="" class="btn btn-primary btn-link btn-sm">Join Team</a>'
                            }
                            else {
                                return '<button class="btn btn-warning">No Tean is There</button>'
                            }
                            }, "autoWidth": true
                    }
                ],
                dom: "Bfrtip",
                "pageLength":10,
                "columnDefs": [{
                    "targets": [3], // column index (start from 0)
                    "orderable": false, // set orderable false for selected columns
                }]
            });

            $('.search-input').on('keyup change', function () {
                var index = $(this).attr('data-column'),
                    val = $(this).val();
                table.columns(index).search(val.trim()).draw();
            });


        });
    </script>
}

RR.Web/Views/Team/TeamFormation.cshtml
@model RR.Dto.Team.TeamFormationDto
@{
    ViewData["Title"] = "Team Formation";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string userId = ViewBag.userId;
}

<section class="section parallax-container breadcrumbs-wrap" data-parallax-img="/images/bg-breadcrumbs-1-1920x726.jpg">
    <div class="parallax-content breadcrumbs-custom context-dark">
        <div class="container">
            <h3 class="breadcrumbs-custom-title">Team Formation</h3>
        </div>
    </div>
</section>

<section class="section section-variant-1 bg-gray-100">
    <div class="container">
        <div class="row row-50">
            <div class="col-sm-12">
                <div class="bg-white">
                    <div class="col-md-12 float-left teamformationdetail">
                        @if (!string.IsNullOrEmpty(ViewBag.TeamUpdateError))
                        {
                            <div class="row row-30 justify-content-center" style="text-align:center;">
                                <div class="col-xl-10">
                                    <h2><span class="text-primary">Timeout!!!</span></h2>
                                    <p class="big text-gray-800">@ViewBag.TeamUpdateError</p>
                                    <a class="button button-lg button-primary" href="/events">Back</a>
                                </div>
                            </div>
                        }
                        else
                        {
                            <!-- Bootstrap tabs-->
                            @if (Model != null && Model.BullList.Count > 0 && Model.RiderList.Count > 0 && !Model.IsFinished)
                            {
                                if (Model.IsAlreadyJoined)
                                {
                                    <div class="row row-30 justify-content-center" style="text-align:center;">
                                        <div class="col-xl-10">
                                            <h2><span class="text-primary">Oops!!!</span></h2>
                                            <p class="big text-gray-800">You have already joined this contest.</p>
                                            <a class="button button-lg button-primary" href="/events">Go to event page</a>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="tabs-custom tabs-horizontal tabs-corporate product-single-additional">
                                        <!-- Nav tabs-->
                                        <ul class="nav nav-tabs" role="tablist">
                                            <li class="nav-item" role="tab"><a class="nav-link custom-tab-a active" href="#tabs-product-1" data-toggle="tab">BIG TEAM CONTEST</a></li>
                                            @*<li class="nav-item" role="tab"><a class="nav-link custom-tab-a" href="#tabs-product-2" data-toggle="tab">3x3 CONTEST</a></li>*@
                                        </ul>
                                        <!-- Tab panes-->

                                        <div class="tab-content">
                                            <div class="tab-pane active show fade" id="tabs-product-1" role="tabpanel">
                                                <!-- Tabs Modern-->
                                                @{ await Html.RenderPartialAsync("_BigTeam", Model); }
                                            </div>
                                            @*<div class="tab-pane fade" id="tabs-product-2" role="tabpanel">
                               @{ await Html.RenderPartialAsync("_3-3Team", Model); }
                            </div>*@
                                            <button type="submit" data-contesttype="@((int)RR.Core.Enums.ContestType.BigTeamContest)" data-eventid="@Model.EventId" data-contestId="@Model.ContestId" onclick="return createTeam(this,'@userId','@(ViewBag.teamId > 0)')" class="btn btn-warning">Submit</button>
                                        </div>

                                    </div>
                                }
                            }
                            else
                            {
                                if (Model.IsFinished)
                                {

                                    <div class="row row-30 justify-content-center" style="text-align:center;">
                                        <div class="col-xl-10">
                                            <h2><span class="text-primary">Oops!!!</span> you are late</h2>
                                            <p class="big text-gray-800">You are late. This event already started. Now you can not create team and join contest.</p>
                                            <p class="big text-gray-800">Check other events for more contests to join and win cash</p>
                                            <a class="button button-lg button-primary" href="/events">Go to event page</a>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="row row-30 justify-content-center" style="text-align:center;">
                                        <div class="col-xl-10">
                                            <h2><span class="text-primary">Oops!!!</span></h2>
                                            <p class="big text-gray-800">Team members are not declared yet, Please check later again.</p>
                                            <a class="button button-lg button-primary" href="/events">Back</a>
                                        </div>
                                    </div>
                                }
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{

    <script src="~/js/bootbox.min.js"></script>

    <script src="~/js/Team.js"></script>
    <script>
        function setCookie(th) {
            document.cookie ='Team'+"="+ JSON.stringify(th);
        }

        function getCookie(cname) {
            var name = cname + "=";
            var ca = document.cookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') {
                    c = c.substring(1);
                }
                if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                }
            }
            return "";
        }
        //Old Function
        $(document).ready(function () {
            debugger;
            var teamCreationArr = [[], [], [], [], [], []];

            var riderList = @Json.Serialize(Model.RiderList);

                for (var i = 0; i < riderList.length; i++) {
                    if (riderList[i].isSelected == true) {
                        if (teamCreationArr[0].length == 2 && teamCreationArr[1].length == 2) {
                            teamCreationArr[2].push(riderList[i]);
                        }
                        else if (teamCreationArr[0].length == 2 && teamCreationArr[1].length < 2) {
                            teamCreationArr[1].push(riderList[i]);
                        }
                        else {
                            teamCreationArr[0].push(riderList[i]);
                        }
                }
            }


            var bullList = @Json.Serialize(Model.BullList);
                for (var i = 0; i < bullList.length; i++) {
                    if (bullList[i].isSelected == true) {
                        if (teamCreationArr[3].length ==1 && teamCreationArr[4].length ==1 && teamCreationArr[5].length == 0) {
                            teamCreationArr[5].push(bullList[i]);
                        }
                        else if (teamCreationArr[3].length ==1 && teamCreationArr[4].length < 1) {
                            teamCreationArr[4].push(bullList[i]);
                        }
                        else {
                            teamCreationArr[3].push(bullList[i]);
                    }
                }

            }
            //teamCreationArr = arrangeTeamTier(teamCreationArr);
            setCookie(teamCreationArr);
            console.log(teamCreationArr);
        });

        @*$(document).ready(function () {
            debugger;
            var riderArray = [[], [], []];
            var teamCreationArr = [[], [], [], [], [], []];
            var riderList = @Json.Serialize(Model.RiderList);
                for (var i = 0; i < riderList.length; i++) {
                    if (riderList[i].isSelected == true) {
                        if (riderArray[0].length == 2 && riderArray[1].length == 2) {
                            riderArray[2].push(riderList[i]);
                        }
                        else if (riderArray[0].length == 2 && riderArray[1].length < 2) {
                            riderArray[1].push(riderList[i]);
                        }
                        else {
                            riderArray[0].push(riderList[i]);
                        }
                }
            }

            riderArray.reverse();
            riderArray.forEach((ra, i) => {
                if (ra.length > 0) {
                    ra.forEach((r) =>
                    {
                        teamCreationArr[i].push(r);
                    })
                }
            });

            //teamCreationArr.push(riderArray);

            var bullArray = [[], [], []];
            var bullList = @Json.Serialize(Model.BullList);
                for (var i = 0; i < bullList.length; i++) {
                    if (bullList[i].isSelected == true) {
                        if (bullArray[0].length == 1 && bullArray[1].length == 1 && bullArray[2].length == 0) {
                            bullArray[2].push(bullList[i]);
                        }
                        else if (bullArray[0].length == 1 && bullArray[1].length < 1) {
                            bullArray[1].push(bullList[i]);
                        }
                        else {
                            bullArray[0].push(bullList[i]);
                    }
                }

            }

            bullArray.reverse();
            bullArray.forEach((ba, i) => {
                if (ba.length > 0) {
                    ba.forEach((b) => {
                        teamCreationArr[(i+3)].push(b);
                    })
                }

            });

            setCookie(teamCreationArr);

            console.log(teamCreationArr);
        });*@
    </script>
}